---
- name: Playbook to Install Packages
  hosts: all
  become: true

  tasks:
  - name: Install nginx
    sudo:
     name: nginx
     state: latest
  - name: start nginx
    service:
     name: nginx
     state: started
